10 - Header component without search functionality complete
hannahlivnat/Ask-EDD-Project pull request #29
Opened 2020-10-03 06:56 UTC by utk0730

Fixes #{issue number here}

- [ ] Up to date with 'dev' branch
- [ ] Branch name follows issueNumber-issueName syntax
- [ ] All PR Status checks are successful
- [ ] Peer reviewed and approved

Question? See the [Contributions guidelines](https://github.com/hannahlivnat/Ask-EDD-Project/blob/main/contributing.md).

2020-10-03 07:35 UTC, utk0730 commented
hi @hannahlivnat 
**Errors thrown by ESLint**

1. ESLint is throwing error with this library [React-ionicons](https://www.npmjs.com/package/react-ionicons) . I think something is broken in this library in react/types.
2. Console.log is throwing warning too with current eslint config.

Suggest me the fix ideas for these.

Also, I wanted to know the reason for adding globals.css and globals.css.map files. 
I have changed style import path in _app.js .I think both are related, need help in understanding this

2020-10-03 17:01 UTC, hannahlivnat requested changes
The header looks good! A lint error was being thrown by console.log because we shouldn't have console.logs in production env. Because we're just testing it in this issue, it's fine as it will be replaced later with the actual function before moving this all to the production branch! css.map and css are the scss parser, but I noticed that your branch is working directly with scss instead so they might not be necessary! 

Requesting the following changes: 

- Can you uninstall react-ionicons? The tests are throwing a warning that this library is unmaintained and has issues. If you'd like to use a library, Semantic UI is already installed and https://ionicons.com/ is free to use. I believe the test was erroring because of the yarn lock file not being updated after install. If errors continue, you need to run a yarn update on your branch. 
- update sass to modern variables rather than root. We need to get rid of package.json down the road and just do yarn install rather than npm install, I'll do that down the road. 
- Delete any unused code (apart from the console.log('it works')) rather than commenting it out

2020-10-03 17:22 UTC, utk0730 commented on styles/globals.scss
> +:root{
sure will do. looks more clean this way

2020-10-03 17:23 UTC, utk0730 commented on components/common/custom_input.js
> +  // const { icon,...inputProps } = props;
yeah, I will be replacing icon , so will fix in that

2020-10-03 17:23 UTC, utk0730 commented on components/header.js
> +// import IosSearchOutline from "react-ionicons/lib/IosSearchOutline";
yep noted

2020-10-03 17:30 UTC, hannahlivnat commented
Cool, I'll keep an eye out for those changes. Also, if you'd like to add your name to the contributors section, it is located in the main readme.md!

2020-10-03 18:50 UTC, utk0730 commented on styles/globals.scss
> +:root{
Need help with global sass variables. If I keep them in global.scss file, variables go undefined in other scss files.
I have finished other feedback changes, need some suggestion with global sass variables

2020-10-03 19:53 UTC, utk0730 commented on styles/globals.scss
> +:root{
@hannahlivnat I have worked on feedback changes other than global sass variables setup.Please review them.

2020-10-03 21:11 UTC, hannahlivnat commented on styles/globals.scss
> +:root{
@utk0730 - Heres a couple of useful articles to read regarding this, it just has to do with the scope of global vs module files. Best solution might be to create a 'common' scss file that gets imported into global file and module files wanting to use variables. 

- https://github.com/vercel/next.js/issues/11368

- https://medium.com/clover-platform-blog/modular-scss-and-why-you-need-it-6bb2d8c40fd8

- https://www.thetopsites.net/article/52900207.shtml

2020-10-03 21:19 UTC, hannahlivnat commented on styles/globals.scss
> +:root{
Just reviewed the rest of the changes you made, everything else looks great! Thanks for the super quick turnaround on feedback.

2020-10-04 06:26 UTC, utk0730 commented on styles/globals.scss
> +:root{
Worked on SASS variables setup as following ->
Approach 1 : created a common sass variables file and imported that in global scss file.I expected it to it be used in another other scss modules without implicitly importing there. But this doesn't work.I have to import common sass file in all of my scss module files

Approach 2 : I was looking for a better solution which allows me to import my common scss file only in gloabl scss file and then it can be used in all my other scss modules.

Looks like this need to be setup with next.config or webpack config.I am not sure of this and  need more time to figure out this.

I noticed in feedback comment that you seems to be okay with my first approach. If that is case I will do it by approach 1 or given a time I can try to figure out second way.

For now I have removed global sass variables in my last commit. I will wait for your feedback

2020-10-04 19:17 UTC, hannahlivnat commented on styles/globals.scss
> +:root{
Let's do the first approach for now, I think that will work fine in making variables accessible to all sass files! Second approach is definitely something to think about in the future, perhaps could be a good separate issue.

2020-10-04 19:22 UTC, utk0730 commented on styles/globals.scss
> +:root{
sure. Right on it.
Updating PR in few mins

2020-10-04 20:00 UTC, utk0730 commented on styles/globals.scss
> +:root{
@hannahlivnat  changes pushed. Please have a look

2020-10-04 20:02 UTC, hannahlivnat approved these changes
This looks great! Merging into dev.

2020-10-04 20:02 UTC, merged