11 footer component
hannahlivnat/Ask-EDD-Project pull request #30
Opened 2020-10-06 07:46 UTC by utk0730

Fixes #{issue number here}

- [ ] Up to date with 'dev' branch
- [ ] Branch name follows issueNumber-issueName syntax
- [ ] All PR Status checks are successful
- [ ] Peer reviewed and approved

Question? See the [Contributions guidelines](https://github.com/hannahlivnat/Ask-EDD-Project/blob/main/contributing.md).

2020-10-06 07:55 UTC, utk0730 commented
@hannahlivnat Please review.
I appreciate if you can make this project as per Hacktoberfest new participating rules . Just got an email from digital ocean about new guidelines that will be considered for participation from today onwards -  attaching screenshot for reference 
<img width="565" alt="Screenshot 2020-10-06 at 1 24 17 PM" src="https://user-images.githubusercontent.com/28000030/95174148-48762f00-07d7-11eb-9489-c1ab5633e215.png">

2020-10-06 19:26 UTC, hannahlivnat commented
@utk0730 Sure, I just added the label to my project so your contributions can count! Looking through pr now.

2020-10-06 19:30 UTC, hannahlivnat commented on styles/footerstyle.module.scss
> +.footerWrapper {
nice use of nesting in this style sheet!

2020-10-06 19:35 UTC, utk0730 commented on styles/footerstyle.module.scss
> +.footerWrapper {
chat icon is off, i downloaded svg from figma, it came like that in view, let me know what to do with that !

2020-10-06 19:37 UTC, hannahlivnat requested changes
Everything here looks great, just added some comments about footer links

2020-10-06 19:37 UTC, hannahlivnat commented on constants/page_links.js
> +export const JOBS = "/";
This mock page won't link to any of the outside links displayed on the footer, just serving as mock-up on actual page. Could you remove the footer links?

2020-10-06 19:37 UTC, hannahlivnat commented on constants/footer_links.js
> +import {
same here with links, since this is just mock page the footer "links" could just be <p> tags or disabled links.

2020-10-06 19:37 UTC, hannahlivnat commented on components/footer.js
> +const languageOptions = [
this looks great, nice organization of values!

2020-10-06 19:38 UTC, hannahlivnat commented on styles/footerstyle.module.scss
> +.footerWrapper {
I think the chat icon looks good right now, it's not being utilized until later issue.

2020-10-06 19:53 UTC, utk0730 commented on constants/footer_links.js
> +import {
Shall I reset all the route path to empty string ?  As they are not routing to anywhere now and this will make links disabled

2020-10-06 19:58 UTC, hannahlivnat commented on constants/footer_links.js
> +import {
I would say for simplicity just set the footer links for <p> tags instead of <a> tags, then there's no need to routing or disabling links

2020-10-06 20:02 UTC, utk0730 commented on constants/footer_links.js
> +import {
Ok, I will do these.
And what are the next issues in priority ?

2020-10-06 20:18 UTC, utk0730 commented on constants/footer_links.js
> +import {
OK. I will have a look into Level 1 and 2 issues.
I have updated the PR - changed a tag to p.
I have also reset the route values to empty string as of now otherwise I had to remove Next/Link tag at multiple places and this looked a fair approach to me.

2020-10-06 20:20 UTC, utk0730 commented on constants/page_links.js
> +export const JOBS = "/";
Regarding PR request comment change, Are you asking me to change "11-Footer-component" to "Fixes #11" ?

2020-10-06 20:48 UTC, utk0730 commented on constants/page_links.js
> +export const JOBS = "/";
done done.
 Will take care of these next time :)

2020-10-06 20:51 UTC, hannahlivnat commented on constants/page_links.js
> +export const JOBS = "/";
Awesome! Currently it now says 14, I believe it should be 11.

2020-10-07 20:13 UTC, utk0730 commented
@hannahlivnat I have done all the changes, am I missing anything ?

2020-10-07 21:21 UTC, hannahlivnat approved these changes

2020-10-07 21:21 UTC, merged

2020-10-07 21:22 UTC, hannahlivnat commented
@utk0730 Everything looks good, just merged!