:green_heart: design contact us page
hannahlivnat/Ask-EDD-Project pull request #31
Opened 2020-10-11 04:10 UTC by utk0730

Fixes #{14}

- [ ] Up to date with 'dev' branch
- [ ] Branch name follows issueNumber-issueName syntax
- [ ] All PR Status checks are successful
- [ ] Peer reviewed and approved

Question? See the [Contributions guidelines](https://github.com/hannahlivnat/Ask-EDD-Project/blob/main/contributing.md).

2020-10-11 16:32 UTC, hannahlivnat requested changes
Great work on this page, it looks really nice! Can you link the help-center route to the "Contact" link in the nav bar?

2020-10-11 16:59 UTC, utk0730 commented
> Great work on this page, it looks really nice! Can you link the help-center route to the "Contact" link in the nav bar?

2020-10-11 17:10 UTC, utk0730 commented
@hannahlivnat This is contact us page right ?
Then shouldn't it be linked from contact link in Navbar ?
Further I realise I have to rename some files , and new page to contact us rather than help center 

Give me a clarity on these

2020-10-11 17:16 UTC, hannahlivnat commented
> @hannahlivnat This is contact us page right ?
> Then shouldn't it be linked from contact link in Navbar ?
> Further I realise I have to rename some files , and new page to contact us rather than help center
> 
> Give me a clarity on these

Yes, you can rename help-center route to contact route and it should be linked to "Contact" on the navbar

2020-10-11 17:47 UTC, utk0730 commented
@hannahlivnat changes done. Please review

2020-10-11 18:45 UTC, hannahlivnat requested changes
contact page link working, but main help center link has been disabled

2020-10-11 18:45 UTC, hannahlivnat commented on constants/nav_links.js
> +    enabled: false,
Help Center link is no longer leading to main page, please fix.

2020-10-12 02:31 UTC, utk0730 commented on constants/nav_links.js
> +    enabled: false,
ok,I was confused over which pages should be visible now.
fixed - help center page route.
So we have two route enabled pages - contact page and helpcenter page

2020-10-12 19:16 UTC, utk0730 commented on constants/nav_links.js
> +    enabled: false,
@hannahlivnat review please

2020-10-12 20:03 UTC, hannahlivnat requested changes

2020-10-12 20:03 UTC, hannahlivnat commented on components/contact_page.js
> +import style from "../styles/contactusstyle.module.scss";
@utk0730 added additional review comment here

2020-10-14 21:20 UTC, hannahlivnat requested changes

2020-10-14 21:20 UTC, hannahlivnat commented on components/contact_page.js
> +import { HelpBox } from "../components/common/helpBox";
@utk0730 Wanted to double check that you received my comments on contact_page naming a few days ago?

2020-10-17 18:27 UTC, utk0730 commented on components/contact_page.js
> +import { HelpBox } from "../components/common/helpBox";
Sorry, I havn't been keeping well for past 3-4 days.
About changes, You want me to change components name, and also class names right ?
@hannahlivnat

2020-10-17 18:36 UTC, hannahlivnat commented on components/contact_page.js
> +import { HelpBox } from "../components/common/helpBox";
@utk0730 No worries! Yes, everything having to do with the Contact Page (components/classes) should have the contact-page name and everything having to do with the main help center landing page should have the help-center name.

2020-10-17 19:50 UTC, hannahlivnat approved these changes
Looks great, merging in!

2020-10-17 19:50 UTC, merged